### ISSUE TITLE
Adding contributors

### ISSUE THREAD

**Issue by roerohan** [csivitu/CTF-Write-ups#13]

**Comment by roerohan** [comment]
@all-contributors please add @roerohan for documentation contributions.

**Comment by thebongy** [comment]
Thanks for adding documentation @thebongy cc @all-contributors

**Comment by roerohan** [comment]
@all-contributors please add @thebongy for docs.

**Comment by roerohan** [comment]
Add @sanjaybaskaran01 for docs

**Comment by roerohan** [comment]
@all-contributors add @sanjaybaskaran01 for docs

**Comment by roerohan** [comment]
@all-contributors add @UnknownAbyss for docs
